name: Run script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at 00:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  run:
    runs-on: macos-14
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x
      - run: deno run -A main.ts
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'Update HIDIVE papers'
          title: 'Update HIDIVE papers'
          body: |
            This is an automated pull request to update HIDIVE lab papers from Zotero collections.
          branch: update-papers
          base: main
